# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='manufacturers/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('device_role', models.CharField(choices=[('server', 'Server'), ('switch', 'Network Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('pdu', 'PDU'), ('ups', 'UPS'), ('patch_panel', 'Patch Panel'), ('kvm', 'KVM'), ('storage', 'Storage'), ('tape', 'Tape Library'), ('console', 'Console Server'), ('load_balancer', 'Load Balancer'), ('other', 'Other')], default='server', max_length=30)),
                ('u_height', models.PositiveSmallIntegerField(default=1)),
                ('is_full_depth', models.BooleanField(default=True)),
                ('power_draw_w', models.FloatField(default=0, help_text='Typical power draw in watts')),
                ('max_power_draw_w', models.FloatField(default=0)),
                ('weight_kg', models.FloatField(default=0)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='device_types/front/')),
                ('rear_image', models.ImageField(blank=True, null=True, upload_to='device_types/rear/')),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for visualization', max_length=7)),
                ('airflow', models.CharField(choices=[('front-to-rear', 'Front to Rear'), ('rear-to-front', 'Rear to Front'), ('passive', 'Passive'), ('side', 'Side')], default='front-to-rear', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_types', to='assets.manufacturer')),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_u', models.PositiveSmallIntegerField(blank=True, help_text='Lowest U position (1-indexed from bottom)', null=True)),
                ('face', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear')], default='front', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('staged', 'Staged'), ('failed', 'Failed'), ('decommissioning', 'Decommissioning'), ('offline', 'Offline')], default='active', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('management_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('cpu_cores', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ram_gb', models.FloatField(blank=True, null=True)),
                ('storage_tb', models.FloatField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expires', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vendor_order_number', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='assets.devicetype')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='locations.rack')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interface_type', models.CharField(choices=[('1000base-t', '1000BASE-T (1GE)'), ('10gbase-t', '10GBASE-T (10GE)'), ('25gbase-x-sfp28', 'SFP28 (25GE)'), ('40gbase-x-qsfpp', 'QSFP+ (40GE)'), ('100gbase-x-qsfp28', 'QSFP28 (100GE)'), ('sfp', 'SFP (1GE Optical)'), ('fiber-lc', 'Fiber (LC)'), ('fiber-sc', 'Fiber (SC)'), ('console', 'Console'), ('mgmt', 'Management'), ('power', 'Power'), ('virtual', 'Virtual'), ('other', 'Other')], default='1000base-t', max_length=30)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='assets.device')),
            ],
            options={
                'unique_together': {('device', 'name')},
            },
        ),
    ]
