# Generated by Django 4.2.9 on 2026-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_devicetype_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/front/'),
        ),
        migrations.AddField(
            model_name='device',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/rear/'),
        ),
    ]
