# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_count', models.PositiveSmallIntegerField(default=24)),
                ('port_type', models.CharField(default='rj45', max_length=30)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patch_panel_info', to='assets.device')),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_a_id', models.PositiveBigIntegerField(null=True)),
                ('termination_b_id', models.PositiveBigIntegerField(null=True)),
                ('cable_type', models.CharField(choices=[('cat5e', 'CAT5e'), ('cat6', 'CAT6'), ('cat6a', 'CAT6A'), ('cat8', 'CAT8'), ('mmf', 'Multimode Fiber'), ('smf', 'Single-Mode Fiber'), ('dac', 'DAC (Direct Attach)'), ('power-c13-c14', 'Power C13-C14'), ('power-c19-c20', 'Power C19-C20'), ('power-nema', 'Power NEMA'), ('console', 'Console'), ('other', 'Other')], default='cat6', max_length=30)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('planned', 'Planned'), ('decommissioned', 'Decommissioned')], default='connected', max_length=20)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color', max_length=7)),
                ('length', models.FloatField(blank=True, help_text='Cable length in meters', null=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('termination_a_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cable_termination_a', to='contenttypes.contenttype')),
                ('termination_b_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cable_termination_b', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['cable_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PatchPanelPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rear_port_position', models.PositiveSmallIntegerField(default=1)),
                ('patch_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='cables.patchpanel')),
            ],
            options={
                'unique_together': {('patch_panel', 'name')},
            },
        ),
    ]
