# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature', 'Temperature'), ('power', 'Power'), ('connectivity', 'Connectivity'), ('capacity', 'Capacity'), ('hardware', 'Hardware'), ('other', 'Other')], default='other', max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SNMPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField(default=161)),
                ('snmp_version', models.CharField(choices=[('v1', 'SNMPv1'), ('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=5)),
                ('community', models.CharField(default='public', max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('last_polled', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_config', to='assets.device')),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('cpu_util', 'CPU Utilization'), ('mem_util', 'Memory Utilization'), ('power_draw', 'Power Draw (W)'), ('temperature', 'Temperature (°C)'), ('bandwidth_in', 'Bandwidth In (Mbps)'), ('bandwidth_out', 'Bandwidth Out (Mbps)'), ('disk_util', 'Disk Utilization'), ('fan_speed', 'Fan Speed (RPM)')], max_length=30)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='assets.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
