# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('total_power_kw', models.FloatField(default=0)),
                ('total_cooling_tons', models.FloatField(default=0)),
                ('pue', models.FloatField(default=1.5, help_text='Power Usage Effectiveness')),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('server', 'Server Room'), ('network', 'Network Room'), ('storage', 'Storage Room'), ('mixed', 'Mixed')], default='server', max_length=20)),
                ('width', models.FloatField(default=20, help_text='Width in meters')),
                ('height', models.FloatField(default=20, help_text='Height (depth) in meters')),
                ('floor_number', models.IntegerField(default=1)),
                ('raised_floor', models.BooleanField(default=True)),
                ('raised_floor_height', models.FloatField(default=0.6, help_text='Raised floor height in meters')),
                ('max_power_kw', models.FloatField(default=0)),
                ('max_cooling_tons', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='locations.datacenter')),
            ],
            options={
                'ordering': ['datacenter', 'name'],
                'unique_together': {('datacenter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20)),
                ('position_x', models.FloatField(default=0, help_text='X position on floor plan in meters')),
                ('position_y', models.FloatField(default=0, help_text='Y position on floor plan in meters')),
                ('notes', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='locations.room')),
            ],
            options={
                'ordering': ['room', 'name'],
                'unique_together': {('room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('reserved', 'Reserved'), ('decommissioned', 'Decommissioned')], default='active', max_length=20)),
                ('u_height', models.PositiveIntegerField(default=42, help_text='Total rack height in U')),
                ('width', models.FloatField(default=0.6, help_text='Width in meters')),
                ('depth', models.FloatField(default=1.0, help_text='Depth in meters')),
                ('max_weight_kg', models.FloatField(default=1000)),
                ('max_power_kw', models.FloatField(default=20)),
                ('position_x', models.FloatField(default=0, help_text='X position in row (meters)')),
                ('position_y', models.FloatField(default=0, help_text='Y position on floor plan')),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='locations.row')),
            ],
            options={
                'ordering': ['row', 'name'],
                'unique_together': {('row', 'name')},
            },
        ),
    ]
