# Generated by Django 4.2.9 on 2026-03-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='doors',
            field=models.JSONField(blank=True, default=list, help_text='[{wall:"top"|"bottom"|"left"|"right", position:float, width:float}]'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('server', 'Server Room'), ('network', 'Network Room'), ('storage', 'Storage Room'), ('idf', 'IDF (Intermediate Distribution Frame)'), ('mdf', 'MDF (Main Distribution Frame)'), ('colocation', 'Colocation'), ('mixed', 'Mixed')], default='server', max_length=20),
        ),
    ]
