# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('incoming_power_kw', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_panels', to='locations.datacenter')),
            ],
            options={
                'ordering': ['datacenter', 'name'],
                'unique_together': {('datacenter', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PowerFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('planned', 'Planned'), ('failed', 'Failed'), ('offline', 'Offline')], default='active', max_length=20)),
                ('supply', models.CharField(choices=[('ac', 'AC'), ('dc', 'DC')], default='ac', max_length=10)),
                ('phase', models.CharField(choices=[('single-phase', 'Single Phase'), ('three-phase', 'Three Phase')], default='single-phase', max_length=20)),
                ('voltage', models.PositiveSmallIntegerField(default=208)),
                ('amperage', models.PositiveSmallIntegerField(default=30)),
                ('max_utilization', models.FloatField(default=80, help_text='Max utilization percentage')),
                ('is_redundant', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('power_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='power.powerpanel')),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_feeds', to='locations.rack')),
                ('redundant_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='power.powerfeed')),
            ],
            options={
                'ordering': ['power_panel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PDU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdu_type', models.CharField(choices=[('basic', 'Basic'), ('metered', 'Metered'), ('switched', 'Switched'), ('monitored', 'Monitored'), ('smart', 'Smart')], default='basic', max_length=20)),
                ('outlets_count', models.PositiveSmallIntegerField(default=16)),
                ('max_amperage', models.FloatField(default=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('inlet_type', models.CharField(blank=True, max_length=50)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdu_info', to='assets.device')),
                ('power_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdus', to='power.powerfeed')),
            ],
        ),
        migrations.CreateModel(
            name='PowerOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('outlet_type', models.CharField(choices=[('nema-5-15r', 'NEMA 5-15R'), ('nema-5-20r', 'NEMA 5-20R'), ('nema-l5-20r', 'NEMA L5-20R'), ('nema-l5-30r', 'NEMA L5-30R'), ('nema-l6-20r', 'NEMA L6-20R'), ('iec-60320-c13', 'IEC 60320 C13'), ('iec-60320-c19', 'IEC 60320 C19'), ('other', 'Other')], default='iec-60320-c13', max_length=30)),
                ('power_draw_w', models.FloatField(default=0, help_text='Current power draw in watts')),
                ('feed_leg', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('connected_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_outlets', to='assets.device')),
                ('pdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='power.pdu')),
            ],
            options={
                'unique_together': {('pdu', 'name')},
            },
        ),
    ]
