# Generated by Django 4.2.9 on 2026-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('rack-front', 'Rack Front'), ('rack-rear', 'Rack Rear'), ('rack-top', 'Rack Top'), ('room', 'Room'), ('cooling-supply', 'Cooling Supply'), ('cooling-return', 'Cooling Return')], default='rack-front', max_length=20)),
                ('current_temp_c', models.FloatField(default=0)),
                ('threshold_high_c', models.FloatField(default=30)),
                ('threshold_critical_c', models.FloatField(default=35)),
                ('threshold_low_c', models.FloatField(default=15)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_sensors', to='locations.rack')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_sensors', to='locations.room')),
            ],
        ),
        migrations.CreateModel(
            name='HumidityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rh', models.FloatField(help_text='Relative humidity %')),
                ('threshold_high', models.FloatField(default=70)),
                ('threshold_low', models.FloatField(default=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humidity_readings', to='locations.room')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='CoolingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('crac', 'CRAC (Computer Room Air Conditioner)'), ('crah', 'CRAH (Computer Room Air Handler)'), ('in-row', 'In-Row Cooling'), ('overhead', 'Overhead Cooling'), ('rear-door', 'Rear Door Heat Exchanger'), ('chiller', 'Chiller')], default='crac', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('cooling_capacity_kw', models.FloatField(default=0, help_text='Cooling capacity in kW')),
                ('cooling_capacity_tons', models.FloatField(default=0, help_text='Cooling capacity in tons')),
                ('power_draw_kw', models.FloatField(default=0)),
                ('airflow_cfm', models.FloatField(default=0, help_text='Airflow in CFM')),
                ('supply_temp_c', models.FloatField(default=16, help_text='Supply air temperature in Celsius')),
                ('return_temp_c', models.FloatField(default=24, help_text='Return air temperature in Celsius')),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooling_units', to='locations.room')),
            ],
            options={
                'ordering': ['room', 'name'],
            },
        ),
    ]
